<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
        <LangVersion>default</LangVersion>

        <!-- AOT 相关配置 -->
        <!-- <PublishAot>true</PublishAot>
        <TrimMode>full</TrimMode>
        <InvariantGlobalization>true</InvariantGlobalization>
        <IlcGenerateStackTraceData>false</IlcGenerateStackTraceData>
        <IlcOptimizationPreference>Size</IlcOptimizationPreference>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
        
        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault> -->
    </PropertyGroup>

    <ItemGroup>
        <RdXmlFile Include="rd.xml" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\StarBlogPublisher.Core\StarBlogPublisher.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.2" />
        <PackageReference Include="Avalonia.AvaloniaEdit" Version="12.0.0" />
        <PackageReference Include="Avalonia.Browser" Version="12.1.2" />
        <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.1.2" />
        <PackageReference Include="Avalonia.Controls.WebView" Version="12.1.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FluentAvaloniaUI" Version="3.1.0" />
        <PackageReference Include="FluentIcons.Avalonia.Fluent" Version="2.1.339.1" />
        <PackageReference Include="Optris.Icons.Avalonia.FontAwesome" Version="12.0.7" />
        <PackageReference Include="ReactiveUI" Version="24.1.0" />
        <PackageReference Include="Sdcb.WordCloud" Version="2.0.1" />
    </ItemGroup>
</Project>
